baseURL      = "https://balisquad.com/blog/"
languageCode = "en-us"
title        = "BaliSquad"

defaultContentLanguage = "en"
hasCJKLanguage = false

[pagination]
    pagerSize = 5

[permalinks]
    post = "/p/:slug/"
    page = "/:slug/"
