mainSections   = ["post"]
rssFullContent = true

[footer]
    since = 2024

[sidebar]
    emoji    = "üèùÔ∏è"
    subtitle = "Discover events and connect with people in Bali"

[article]
    headingAnchor = true
    toc           = true
    readingTime   = true
    
    [article.license]
        enabled = false

[widgets]
    homepage = [
        { type = "search" },
        { type = "archives", params = { limit = 5 } },
        { type = "categories", params = { limit = 10 } },
        { type = "tag-cloud", params = { limit = 10 } },
    ]
    page = [{ type = "toc" }]

[comments]
    enabled = false

[colorScheme]
    toggle  = true
    default = "auto"

[imageProcessing.cover]
    enabled = true

[imageProcessing.content]
    enabled = true
