baseURL = 'https://balisquad.com/blog/'
relativeURLs = true
canonifyURLs = false
languageCode = 'en-us'
title = 'BaliSquad'
theme = 'paper'

[params]
  instagram = 'balisquad.id'
  images = ['og-image.png']

[menu]
  [[menu.main]]
    identifier = 'about'
    name = 'About'
    url = '/about/'
    weight = 10
