baseURL = 'https://balisquad.com/blog/'
languageCode = 'en-us'
title = 'BaliSquad'
theme = 'paper'

[params]
  instagram = 'balisquad.id'

[menu]
  [[menu.main]]
    identifier = 'about'
    name = 'About'
    url = '/about/'
    weight = 10
